# Ultralytics YOLO 训练配置：只调整训练增强，不做困难类离线增强

task: detect
mode: train

model: yolov8m.pt
data: neu_det.yaml
device: 0
pretrained: true

epochs: 200
batch: 24
imgsz: 640

lr0: 0.001
patience: 50
optimizer: AdamW
momentum: 0.937
weight_decay: 0.0005

warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1

workers: 8
cache: true
amp: true
cos_lr: true

# 最后 30 个 epoch 关闭 Mosaic
close_mosaic: 30

# 只做训练过程中的在线增强
mosaic: 0.4
mixup: 0.0

hsv_h: 0.015
hsv_s: 0.3
hsv_v: 0.2

degrees: 5.0
translate: 0.1
scale: 0.3
shear: 0.0

flipud: 0.5
fliplr: 0.5

project: runs/detect
name: neu_det_yolov8m_train_aug_only
exist_ok: false
save: true