#!/usr/bin/env python3
"""
MVTec AD 数据集转换 - 脚本 4: 生成 YOLO 配置文件
生成 data.yaml 和 class_mapping.txt
注意：现在使用 train/val 结构（不再使用 test）
"""

import re
from pathlib import Path


# 类别缺陷映射表 (与 02_generate_labels.py 保持一致)
CATEGORY_DEFECT_TO_ID = {
    # bottle (3)
    "bottle__broken_large": 0, "bottle__broken_small": 1, "bottle__contamination": 2,
    # cable (8)
    "cable__bent_wire": 3, "cable__cable_swap": 4, "cable__combined": 5,
    "cable__cut_inner_insulation": 6, "cable__cut_outer_insulation": 7,
    "cable__missing_cable": 8, "cable__missing_wire": 9, "cable__poke_insulation": 10,
    # capsule (5)
    "capsule__crack": 11, "capsule__faulty_imprint": 12, "capsule__poke": 13,
    "capsule__scratch": 14, "capsule__squeeze": 15,
    # carpet (5)
    "carpet__color": 16, "carpet__cut": 17, "carpet__hole": 18,
    "carpet__metal_contamination": 19, "carpet__thread": 20,
    # grid (5)
    "grid__bent": 21, "grid__broken": 22, "grid__glue": 23,
    "grid__metal_contamination": 24, "grid__thread": 25,
    # hazelnut (4)
    "hazelnut__crack": 26, "hazelnut__cut": 27, "hazelnut__hole": 28, "hazelnut__print": 29,
    # leather (6)
    "leather__color": 30, "leather__cut": 31, "leather__fold": 32,
    "leather__glue": 33, "leather__poke": 34,
    # metal_nut (4)
    "metal_nut__bent": 35, "metal_nut__color": 36, "metal_nut__flip": 37, "metal_nut__scratch": 38,
    # pill (7)
    "pill__color": 39, "pill__combined": 40, "pill__contamination": 41,
    "pill__crack": 42, "pill__faulty_imprint": 43, "pill__pill_type": 44, "pill__scratch": 45,
    # screw (5)
    "screw__manipulated_front": 46, "screw__scratch_head": 47,
    "screw__scratch_neck": 48, "screw__thread_side": 49, "screw__thread_top": 50,
    # toothbrush (1)
    "toothbrush__defective": 51,
    # transistor (4)
    "transistor__bent_lead": 52, "transistor__cut_lead": 53,
    "transistor__damaged_case": 54, "transistor__misplaced": 55,
    # wood (5)
    "wood__color": 56, "wood__combined": 57, "wood__hole": 58, "wood__liquid": 59, "wood__scratch": 60,
    # zipper (7)
    "zipper__broken_teeth": 61, "zipper__combined": 62, "zipper__fabric_border": 63,
    "zipper__fabric_interior": 64, "zipper__rough": 65, "zipper__split_teeth": 66, "zipper__squeezed_teeth": 67,
    # tile (5)
    "tile__crack": 68, "tile__glue_strip": 69, "tile__gray_stroke": 70, "tile__oil": 71, "tile__rough": 72,
}


def extract_classes_from_labels(labels_dir: Path) -> set:
    """
    从标注文件名中提取所有出现的类别

    文件名格式: <category>__<defect>__<image_name>.txt
    """
    classes = set()
    pattern = re.compile(r'^([^_]+__[^_]+)__')

    if not labels_dir.exists():
        return classes

    # 扫描 train 目录
    train_labels_dir = labels_dir / "train"
    if train_labels_dir.exists():
        for label_file in train_labels_dir.rglob("*.txt"):
            match = pattern.match(label_file.stem)
            if match:
                classes.add(match.group(1))

    # 扫描 val 目录
    val_labels_dir = labels_dir / "val"
    if val_labels_dir.exists():
        for label_file in val_labels_dir.rglob("*.txt"):
            match = pattern.match(label_file.stem)
            if match:
                classes.add(match.group(1))

    return classes


def generate_yaml(class_mapping: dict, output_path: Path, relative_path: str = "YOLOv8_data/mvtec_yolo"):
    """生成 data.yaml 文件"""
    yaml_content = f"""# MVTec AD Dataset for YOLOv8 Training
# MVTec License: CC BY-NC-SA 4.0
# Auto-generated by 04_generate_yaml.py
# 数据划分: train/val (80%/20%) - 所有数据合并后分层随机划分

path: {relative_path}
train: images/train
val: images/val

nc: {len(class_mapping)}
names:
"""

    # 按 class_id 排序添加类别
    for class_id in sorted(class_mapping.keys(), key=lambda x: int(x)):
        class_name = class_mapping[class_id]
        yaml_content += f"  {class_id}: {class_name}\n"

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(yaml_content)


def generate_class_mapping_file(class_mapping: dict, output_path: Path):
    """生成 class_mapping.txt 文件"""
    lines = []
    for class_id in sorted(class_mapping.keys(), key=lambda x: int(x)):
        class_name = class_mapping[class_id]
        lines.append(f"{class_id}: {class_name}")

    content = "MVTec AD → YOLOv8 类别映射表\n"
    content += "=" * 50 + "\n"
    content += f"总共 {len(class_mapping)} 个类别\n"
    content += "=" * 50 + "\n"
    content += "\n".join(lines)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)


def main():
    """主函数"""
    print("=" * 60)
    print("MVTec AD → YOLOv8 数据集转换")
    print("脚本 4: 生成 YOLO 配置文件")
    print("=" * 60)

    # 设置路径
    SCRIPT_DIR = Path(__file__).parent
    WORKSPACE_DIR = SCRIPT_DIR.parent
    YOLO_OUTPUT = WORKSPACE_DIR / "YOLOv8_data" / "mvtec_yolo"
    LABELS_DIR = YOLO_OUTPUT / "labels"

    if not LABELS_DIR.exists():
        print(f"[错误] 标注目录不存在: {LABELS_DIR}")
        print("  请先运行脚本 2 生成标注文件")
        return

    # 提取所有类别
    print("\n扫描标注文件...")
    extracted_classes = extract_classes_from_labels(LABELS_DIR)

    if not extracted_classes:
        print("[错误] 未找到任何标注文件")
        print("  请先运行脚本 2 生成标注文件")
        return

    print(f"找到 {len(extracted_classes)} 个类别")

    # 统计各子集文件数
    train_count = len(list((LABELS_DIR / "train").glob("*.txt"))) if (LABELS_DIR / "train").exists() else 0
    val_count = len(list((LABELS_DIR / "val").glob("*.txt"))) if (LABELS_DIR / "val").exists() else 0
    print(f"  - train: {train_count} 个标注文件")
    print(f"  - val: {val_count} 个标注文件")

    # 构建类别映射
    class_mapping = {}
    for class_name in sorted(extracted_classes):
        if class_name in CATEGORY_DEFECT_TO_ID:
            class_id = CATEGORY_DEFECT_TO_ID[class_name]
        else:
            print(f"[警告] 未知类别: {class_name}，跳过")
            continue
        class_mapping[class_id] = class_name

    # 检查是否有缺失的类别
    known_classes = set(CATEGORY_DEFECT_TO_ID.keys())
    missing_classes = known_classes - set(extracted_classes)
    if missing_classes:
        print(f"\n提示: 以下 {len(missing_classes)} 个类别在标注文件中未出现:")
        for cls in sorted(list(missing_classes)[:10]):
            print(f"  - {cls}")
        if len(missing_classes) > 10:
            print(f"  ... 还有 {len(missing_classes) - 10} 个")

    # 统计有标注 vs 空标注
    defect_count = 0
    empty_count = 0
    for label_file in (LABELS_DIR / "train").glob("*.txt"):
        if label_file.stat().st_size == 0:
            empty_count += 1
        else:
            defect_count += 1
    for label_file in (LABELS_DIR / "val").glob("*.txt"):
        if label_file.stat().st_size == 0:
            empty_count += 1
        else:
            defect_count += 1

    print(f"\n标注统计:")
    print(f"  - 有标注（缺陷样本）: {defect_count} 个")
    print(f"  - 空标注（正常样本）: {empty_count} 个")

    # 生成 data.yaml
    yaml_path = YOLO_OUTPUT / "data.yaml"
    print(f"\n生成 {yaml_path}...")
    generate_yaml(class_mapping, yaml_path)
    print(f"[OK] data.yaml 已生成 ({len(class_mapping)} 个类别)")

    # 生成 class_mapping.txt
    mapping_path = YOLO_OUTPUT / "class_mapping.txt"
    print(f"生成 {mapping_path}...")
    generate_class_mapping_file(class_mapping, mapping_path)
    print(f"[OK] class_mapping.txt 已生成")

    # 输出汇总
    print("\n" + "-" * 60)
    print("【配置文件生成汇总】")
    print(f"  类别总数: {len(class_mapping)}")
    print(f"  标注总数: {train_count + val_count}")
    print(f"    - train: {train_count}")
    print(f"    - val: {val_count}")
    print(f"  输出文件:")
    print(f"    - {yaml_path.relative_to(WORKSPACE_DIR)}")
    print(f"    - {mapping_path.relative_to(WORKSPACE_DIR)}")
    print("-" * 60)

    # 列出所有类别
    print("\n类别列表:")
    for class_id in sorted(class_mapping.keys(), key=lambda x: int(x)):
        print(f"  {class_id:2d}: {class_mapping[class_id]}")

    print("\n" + "=" * 60)
    print("[OK] 配置文件生成完成！")
    print("=" * 60)
    print("""
下一步: 可选运行脚本 5 一键转换，或直接开始训练

训练命令:
  yolo detect train data=YOLOv8_data/mvtec_yolo/data.yaml \\
    model=yolov8m.pt epochs=100 imgsz=512 batch=8 device=0

或使用 Python API:
  from ultralytics import YOLO
  model = YOLO('yolov8m.pt')
  results = model.train(data='YOLOv8_data/mvtec_yolo/data.yaml', epochs=100, imgsz=512)
""")


if __name__ == "__main__":
    main()
